<html>
    <head>
        <title>About page.</title>
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <link rel="stylesheet" href="styles.css">
    </head>
    <body>
<div class="container">
  <div class="row" style="font-size: large;border: 2px solid black">
                <?php
            include("nav.html");
            ?>
  </div>
    <div class="row" style="border:2px solid black">
              
               <div class="row" style="border: 1px solid blue">
              <div class="col-lg-4" style="border: 1px solid rgb(68, 193, 204) ">
     <div class="card" style="background-color: rgb(71, 174, 140);">

        .<div class="card-body">
          <div class="card-title" style="font-size: xx-large;">
            <b>Why I love programming</b></div>
          <p>Below are programming languages</p>
          <ul type=" black circle">
            <il><p class="card-text">Javascript</p></il>
            <il><p class="card-text">Python</p></il>
            <il><p class="card-text">Ruby</p></il>
            <il><p class="card-text">Swift</p></il>
            <il><p class="card-text">Java</p></il>
            <il><p class="card-text">Etc.</p></il>
           
          </ul>
        </div>
      .</div>
</div>
</div>
    
    <div class="col-lg-4" style="border: 1px solid rgb(93, 137, 177) ">
    <img src="image3.jpg" height= 200 width=100>
                    </div>
                   
                    <div class="col-lg-4" style="border: 1px solid rgb(42, 119, 163) ">
                    <p style="font-size: xx-large;font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;"><B>This web is mainly created to advertise products in our store<br />
                    The business idea was just created a few weeks ago<br />
                     For more Information please go to the contact page </B></p>
                    </div>
</div>
  
                <div class="row" style="border: 1px solid blue">
                   <marquee direction="right"><p style="font-size: large; ;"><b>This website is maintained and managed by the head of product-cataloque<br />
                    for more information please contact us using the details in the contact page</b></p>
                   </marquee>     
                    </div>
                </button>
               </nav>
            </div>
</div>
    </body>
</html>


